name       : crystal
version    : 1.4.1
release    : 1
source     :
    - https://github.com/crystal-lang/crystal/archive/refs/tags/1.4.1.tar.gz : 97466656adede19943619e18af030c1d542c2c3dd1f36f3a422310bd8b53f5e0
    - https://github.com/crystal-lang/crystal/releases/download/1.4.0/crystal-1.4.0-1-linux-x86_64.tar.gz : 044ab8d89dffc356faeccbdcbbd9d4e033545a5f404a17c4997dc62e39f86b7e   # remove post-boostrap
homepage   : https://crystal-lang.org
license    : Apache-2.0
component  : programming
summary    : The Crystal programming language
description: |
    Crystal is a programming language with similar syntax to Ruby, static type-checking, the ability to call C code, compile-time evaluation and generation of code, and the ability to compile to native code.
networking : yes  # for tests
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(libevent)
    - pkgconfig(libxml-2.0)
    - pkgconfig(yaml-0.1)
    # - crystal
    - git
    - llvm-devel
build      : |
    # remove post-boostrap
    tar xf $sources/crystal-1.4.0-1-linux-x86_64.tar.gz --directory /tmp
    export PATH="$PATH:/tmp/crystal-1.4.0-1/bin"
    # ---
   
    %make \
      release=1 \
      CRYSTAL_PATH="$workdir/src" \
      CRYSTAL_CONFIG_VERSION="$version" \
      CRYSTAL_CONFIG_PATH="lib:%libdir%/crystal" \
      CRYSTAL_CONFIG_TARGET=x86_64-linux-gnu
install    : |
    install -Dm755 .build/crystal $installdir/usr/bin/crystal

    install -dm755 $installdir%libdir%/crystal
    cp -aT src $installdir%libdir%/crystal
check      : |
    rm spec/std/file_spec.cr spec/compiler/ffi/ffi_spec.cr  # tests fail in solbuild
    %make std_spec

    git init  # for some reason compiler specs need a git repo
    %make compiler_spec CRYSTAL_CONFIG_TARGET=x86_64-linux-gnu
