name       : crystal
version    : 1.8.2
release    : 9
source     :
    - https://github.com/crystal-lang/crystal/archive/refs/tags/1.8.2.tar.gz : 6e722e3239a8c467ba42a8838916788a4795b0ceaa2d1e2e98616cedeb540605
homepage   : https://crystal-lang.org
license    : Apache-2.0
component  : programming
summary    : The Crystal programming language
description: |
    Crystal is a programming language with similar syntax to Ruby, static type-checking, the ability to call C code, compile-time evaluation and generation of code, and the ability to compile to native code.
networking : yes  # for tests
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(libevent)
    - pkgconfig(libxml-2.0)
    - pkgconfig(yaml-0.1)
    - crystal
    - git
    - llvm-devel
rundeps    :
    - bdwgc-devel
    - libevent-devel
build      : |
    %make \
      release=1 \
      interpreter=1 \
      CRYSTAL_PATH="lib:$workdir/src" \
      CRYSTAL_CONFIG_VERSION="$version" \
      CRYSTAL_CONFIG_PATH="lib:%libdir%/crystal/src" \
      CRYSTAL_CONFIG_TARGET=x86_64-linux-gnu
install    : |
    %make_install \
      DATADIR=$installdir%libdir%/crystal \
      BINDIR=$installdir/usr/bin \
      PREFIX=/usr

    rm -r $installdir/usr/share/licenses
check      : |
    rm spec/std/file_spec.cr spec/compiler/ffi/ffi_spec.cr  # tests fail in solbuild
    %make std_spec CRYSTAL_CONFIG_TARGET=x86_64-linux-gnu

    git init --quiet  # for some reason compiler specs need a git repo
    %make compiler_spec CRYSTAL_CONFIG_TARGET=x86_64-linux-gnu
