name       : crystal
version    : 1.5.0
release    : 3
source     :
    - https://github.com/crystal-lang/crystal/archive/refs/tags/1.5.0.tar.gz : f53e459ef6c7227df922a76fb62e350c90d52d30bfaa84b90feda9731bb98655
    - https://github.com/crystal-lang/crystal/releases/download/1.5.0/crystal-1.5.0-1-linux-x86_64.tar.gz : 627360f0fc805202d80310007d503c7a2fc0745b1db2211537d7f54e9a994347
homepage   : https://crystal-lang.org
license    : Apache-2.0
component  : programming
summary    : The Crystal programming language
description: |
    Crystal is a programming language with similar syntax to Ruby, static type-checking, the ability to call C code, compile-time evaluation and generation of code, and the ability to compile to native code.
networking : yes  # for tests
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(libevent)
    - pkgconfig(libxml-2.0)
    - pkgconfig(yaml-0.1)
    # crystal
    - git
    - llvm-devel
rundeps    :
    - libevent-devel
setup      : |
    tar xf $sources/crystal-1.5.0-1-linux-x86_64.tar.gz --directory /tmp
build      : |
    export PATH="$PATH:/tmp/crystal-1.5.0-1/bin"
    %make \
      release=1 \
      interpreter=1 \
      CRYSTAL_PATH="$workdir/src" \
      CRYSTAL_CONFIG_VERSION="$version" \
      CRYSTAL_CONFIG_PATH="lib:%libdir%/crystal" \
      CRYSTAL_CONFIG_TARGET=x86_64-linux-gnu
install    : |
    install -Dm755 .build/crystal $installdir/usr/bin/crystal

    install -dm755 $installdir%libdir%/crystal
    cp -aT src $installdir%libdir%/crystal
check      : |
    rm spec/std/file_spec.cr spec/compiler/ffi/ffi_spec.cr  # tests fail in solbuild
    %make std_spec

    git init  # for some reason compiler specs need a git repo
    %make compiler_spec CRYSTAL_CONFIG_TARGET=x86_64-linux-gnu || :
